<span class="verification-brand" aria-label="Khronoz">
    <span class="verification-brand-caption">Generated by</span>
    <span class="verification-brand-lockup">
        <svg viewBox="0 0 34 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
            <path d="M1 19.2h32" />
            <rect x="2.6" y="9.6" width="7.4" height="7.4" rx="1.6" fill="currentColor" stroke="none" />
            <rect x="13.3" y="5.2" width="7.4" height="11.8" rx="1.6" fill="currentColor" stroke="none" />
            <rect x="24" y="1.2" width="7.4" height="15.8" rx="1.6" fill="currentColor" stroke="none" />
        </svg>
        <span class="verification-wordmark">khronoz</span>
    </span>
</span>
